### ISSUE TITLE
discuss of registe Faiss.jl

### ISSUE THREAD

**Issue by zsz00** [cjdoris/Faiss.jl#1]
I am a heavy user of  python faiss and julia ann. 
I found this repo, this a very good work . 
I tried to use the Faiss.jl, but functions not enough. 

I base this repo continue develop and improve. https://github.com/zsz00/Faiss.jl
I made a lot of changes and added some common features, Now it's more stable and usable. 
now I want to  registe Faiss.jl, There are two ways:
1. Direct registe https://github.com/zsz00/Faiss.jl. 
2. merge to this repo, and registe it. 

I'd like to hear your comments.  
thank you !!

**Comment by zsz00** [comment]
A few days later, I saw that you did not reply, I guess you are busy, I took the liberty of choosing 1 .
and i  registe  https://github.com/zsz00/Faiss.jl as Faiss.jl

**Comment by cjdoris** [comment]
Hi, sorry for not replying sooner. Sure I don't mind you registering a fork.
